Create BASE models
21F0rc3/PageGuild pull request #2
Opened 2021-12-19 16:57 UTC by fredmnpinto

2021-12-19 17:05 UTC, fredmnpinto commented
@21F0rc3 Dá aqui uma olhadinha se vc discorda de alguma coisa, são as models base só pra colocarmos logo o projeto funcionando e eu já renomeei ela e todos os atributos, mas se me esqueci de algo em portugues avisa

2021-12-19 17:37 UTC, 21F0rc3 requested changes
No geral parece-me bem. Apenas um erro ou 2. A maioria são mais cenas de nomes em que eu coloquei uma coisa, e tu outro. Depois diz-me como fica no whatsapp. 🤙

2021-12-19 17:37 UTC, 21F0rc3 commented on PageGuild/app/Models/Address.php
> +    const CREATED_AT = "register_date";
aqui não é melhor registration_date?

2021-12-19 17:37 UTC, 21F0rc3 commented on PageGuild/app/Models/Address.php
> +    ];
"residence" tambem pode ser fillable acho. E tipo a morada, tipo o nome da rua, numero do predio, porta...

2021-12-19 17:37 UTC, 21F0rc3 commented on PageGuild/app/Models/Book.php
> +        "encadernation"
Não e encadernation, e bookbinding acho. Em inglês fica estranho eu sei

2021-12-19 17:37 UTC, 21F0rc3 commented on PageGuild/app/Models/Editor.php
> +class Editor extends Model
Mano eu troquei Editor por Publisher, porque para mim faz mais sentido. Tipo eu associo mais Editora a Publisher do que Editor. Mas se quiseres deixar assim podes, depois avisa-me no whatsapp como ficou para eu alterar

2021-12-19 17:37 UTC, 21F0rc3 commented on PageGuild/app/Models/Item.php
> +    const UPDATED_AT = "register_date";
Aqui o UPDATED_AT não é update_date?

2021-12-19 17:37 UTC, 21F0rc3 commented on PageGuild/app/Models/Item.php
> +
Não falta algumas relacoes nesta classe? Tipo Com o utilizador, por exemplo, ou com o proprio livro?

2021-12-19 17:37 UTC, 21F0rc3 commented on PageGuild/app/Models/ItemShoppingCart.php
> +        "register_date", "flg_delete", "quantity"
Aqui eu coloquei amount, novamente depois diz-me no whatsapp como ficou

2021-12-19 17:37 UTC, 21F0rc3 commented on PageGuild/app/Models/Shipping.php
> +        "estimated_date", "shipping_state_id"
Aqui eu coloquei expected_date, novamente depois dizme no whats como e que ficou

2021-12-20 14:00 UTC, fredmnpinto commented on PageGuild/app/Models/Item.php
> +
Feito, exceto pela relação com o livro, já que ele não necessariamente é um livro e o livro já possui uma relação com item

2021-12-20 14:01 UTC, fredmnpinto commented on PageGuild/app/Models/Item.php
> +    const UPDATED_AT = "register_date";
oops

2021-12-20 14:03 UTC, fredmnpinto commented on PageGuild/app/Models/Address.php
> +    ];
Puts, na real eu coloquei o campo address como sendo isso, na real. Acho que Residence não é bem de endereço

2021-12-20 16:36 UTC, 21F0rc3 approved these changes
Ta top 👍 Podes tirar o residence que eu não sabia que era o address. Eu troco no meu.

2021-12-20 16:36 UTC, 21F0rc3 commented on PageGuild/app/Models/Address.php
> +    ];
okok vou trocar

2021-12-20 16:36 UTC, 21F0rc3 commented on PageGuild/app/Models/Address.php
> +    ];
sim, tira o residence, não sabia que o address era isso

2021-12-21 21:52 UTC, merged